version: "3.3"
services:
  tb-mysql-db:
    image: rphgoossens/tb-mysql-docker:tb-docker-2.0
    volumes:
      - type: volume
        source: tb-mysql-shared
        target: /var/lib/mysql
    networks:
      - tb-network-backend
  tb-springboot-app-1:
    build: ./tb-springboot-app
    image: rphgoossens/tb-springboot-docker:tb-docker-2.1
    environment:
      - SERVER_PORT=8090
      - DB_USERNAME=tb_admin
      - DB_PASSWORD=tb_admin
      - DB_URL=mysql://tb-mysql-db:3306/db_terrax
    depends_on:
      - tb-mysql-db
    command: ["/wait-for-it.sh", "tb-mysql-db:3306", "--timeout=0", "--", "java","-cp","app:app/lib/*","nl.terrax.tbspringbootdocker.TbSpringbootDockerApplication"]
    networks:
      - tb-network-frontend
      - tb-network-backend
  tb-springboot-app-2:
    build: ./tb-springboot-app
    image: rphgoossens/tb-springboot-docker:tb-docker-2.1
    environment:
      - SERVER_PORT=8090
      - DB_USERNAME=tb_admin
      - DB_PASSWORD=tb_admin
      - DB_URL=mysql://tb-mysql-db:3306/db_terrax
    depends_on:
      - tb-mysql-db
    command: ["/wait-for-it.sh", "tb-mysql-db:3306", "--timeout=0", "--", "java","-cp","app:app/lib/*","nl.terrax.tbspringbootdocker.TbSpringbootDockerApplication"]
    networks:
      - tb-network-frontend
      - tb-network-backend
  tb-nginx:
    image: rphgoossens/tb-nginx-docker:tb-docker-2.0
    ports:
      - "8080:8080"
    depends_on:
      - tb-springboot-app-1
      - tb-springboot-app-2
    networks:
      - tb-network-frontend
volumes:
  tb-mysql-shared:
networks:
  tb-network-frontend:
  tb-network-backend:
